fieldLayouts:
  9a11e876-ad31-4a29-8b2c-c4e0cde15961:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 07374108-a8a7-4005-9fda-8b69ebe7e901
            warning: null
            width: 100
        name: Content
        uid: a41ba6b4-ef21-41b5-b016-6a3b25aadae4
fs: general
handle: websiteContent
name: 'Website Content'
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
