columnSuffix: srdhvvtr
contentColumnType: text
fieldGroup: dc05cb0f-f3bb-4626-89c9-b167ee758fa3 # Blog Post Fields
handle: summary
instructions: 'Enter a brief, one or two sentence post summary.'
name: Summary
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '1'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
