dateModified: 1652912020
email:
  fromEmail: admin@crankd.nz
  fromName: Tradezone
  transportType: craft\mail\transportadapters\Sendmail
fs:
  blog:
    hasUrls: true
    name: Blog
    settings:
      path: '@webroot/assets/blog'
    type: craft\fs\Local
    url: '@web/assets/blog'
  general:
    hasUrls: true
    name: General
    settings:
      path: '@webroot/assets/general'
    type: craft\fs\Local
    url: '@web/assets/genral'
  websiteGuideImages:
    hasUrls: true
    name: 'Website Guide Images'
    settings:
      path: '@webroot/cms-assets/websiteGuideImages'
    type: craft\fs\Local
    url: /cms-assets/websiteGuideImages
meta:
  __names__:
    0ce672be-119f-48a3-a440-24845d748ddf: 'Website Content' # Website Content
    3f88c1d0-df73-4b76-a64e-54581e98462e: Tradezone # Tradezone
    9a5f418d-169c-4f7d-8977-6204ee41c8aa: 'Site Information' # Site Information
    36b7ee56-d439-4b5a-bbad-08a9585109a7: Footer # Footer
    47bb61b1-ef48-42c0-8b2c-a9fb9d4c6aa1: Image # Image
    84fae076-a210-4967-8e1f-2a2f2b20254a: Default # Default
    6767aad8-276f-44af-a0e2-6035fd3315db: Branding # Branding
    656931f9-b112-4a05-988f-be016f9bc47e: Header # Header
    a4106ab6-a1b3-4bb3-b1fb-31b279b65fea: 'Document Body Content' # Document Body Content
    b02561f8-09d7-47d2-8595-524c36789911: 'Site Information' # Site Information
    b134842a-5933-42df-ac59-3d95deb106e8: About # About
    bdb64804-b3e3-4ad0-9ad4-0031ae4d0619: Text # Text
    be597e10-b2b1-4440-858f-0382424ba3bc: 'Site Description' # Site Description
    c13d0cd9-6195-4f60-9770-e575cb3e3b34: 'Help Guides' # Help Guides
    c788f637-2c81-4fd2-a677-e09c8c8620f6: 'Public Schema' # Public Schema
    d49a3f15-31d8-4357-83de-c73f52ec6e32: 'Main Logo' # Main Logo
    d7667796-b743-4617-bd23-836b4cdb569d: About # About
    f31ce003-71e3-493e-bca1-a9ba719ec8a4: Branding # Branding
    f302e876-fdee-47e2-9958-f288a6e646f8: 'Document Body Field' # Document Body Field
    fc4e3b0a-4009-4a52-8058-594d713baa1a: CraftTemplate # CraftTemplate
plugins:
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  vite:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  websitedocumentation:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
    settings:
      name: 'Website Docs'
      structure: 'Help Guides'
system:
  edition: solo
  live: true
  name: Tradezone
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
