fieldLayouts:
  ae4d0b93-b4bf-4d5b-888f-6ff713a2663a:
    tabs:
      -
        elements:
          -
            fieldUid: be597e10-b2b1-4440-858f-0382424ba3bc # Site Description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Information
        sortOrder: 1
handle: siteInformation
name: 'Site Information'
sortOrder: 1
